config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'carts#show', as: 'cart'
  resources :order_items, only: [:create, :update, :destroy]
  resources :customer, only: [:new, :create, :update, :destroy]
  resources :charges, only: [:new, :create]
  get 'login', to: 'session#new', as: 'login'
  post 'login', to: 'session#create', as: 'create_session'
  get 'logout', to: 'session#destroy', as: 'logout'
  get 'signup', to: 'accounts#new', as: 'signup'
  post 'signup', to: 'accounts#create', as: 'accounts'
  get 'process_cart', to: 'carts#process_cart', as: 'process_cart'
  get 'checkout', to: 'carts#checkout', as: 'checkout'
  post 'complete', to: 'carts#complete_order', as: 'complete_order'
  # resources :accounts, only: [:new, :create, :update, :destroy]

  get '/categories/:name/products', to: 'products#by_category', as: 'by_category'
  get '/', to: 'products#index', as: 'index'
  get '/products/:id', to: 'products#show', as: 'show'
  get '/about', to: 'pages#about', as: 'about'
  get '/contact_us', to: 'pages#contact_us', as: 'contact_us'
  # get '/:name', to: 'product#by_category', as: 'product_by_category'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
  belongs_to :province
end

app/models/order.rb
# order class
class Order < ApplicationRecord
  belongs_to :customer
  before_create :set_order_status
  belongs_to :order_status
  has_many :order_items
  before_save :update_subtotal

  def subtotal
    order_items
      .collect { |item| item.valid? ? (item.quantity.to_i * item.unit_price.to_f) : 0 }
      .sum
  end

  private

  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
# order_item class
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true,
                                                       greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def order_present
    errors.add(:order, 'is not a valid order.') if order.nil?
  end

  def product_present
    errors.add(:product, 'is not a valid product.') if product.nil?
  end

  def finalize
    self[:price] = unit_price
  end
end

app/models/order_status.rb
# order status class
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
# product class
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items

  default_scope { where(is_active: true) }

  def self.search(search)
    where('name LIKE ? or description LIKE ?', "%#{search}%", "%#{search}%")
  end

  def self.get_by_category_id(category_id)
    where('category_id = ?', category_id)
  end

  mount_uploader :image_url, ProductUploader
end

app/models/province.rb
# province class
class Province < ApplicationRecord
  has_many :customers
end

app/models/sale_item.rb
class SaleItem < ApplicationRecord
  belongs_to :product
end

app/controllers/carts_controller.rb
# Carts controller
class CartsController < ApplicationController
  before_action :set_current_order
  before_action :calculate_amount, only: [:checkout, :calculate_amount]
  include SessionHelper
  def show
    @order_items = current_order.order_items
  end

  def process_cart
    @order_items = current_order.order_items
  end

  def checkout
    if account_customer_info?
      update_order
    else
      redirect_to(controller: :customer, action: :new)
    end
  end

  def update_order
    customer = current_customer
    @description = 'description of charge'
    @order.update(pst: customer.province.pst / 100,
                  gst: customer.province.gst / 100,
                  hst: customer.province.hst / 100)
    @order_items = current_order.order_items
    @order.save
  end

  def set_current_order
    @order = current_order
  end

  def calculate_amount
    @amount = @order.subtotal + (@order.subtotal * (@order.pst + @order.gst +
              @order.hst))
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in(account)
    session[:user_id] = account.id
  end

  # Returns the current logged-in user (if any).
  def current_account
    @current_account ||= Account.find_by(id: session[:user_id])
  end

  def current_customer
    @current_customer = Customer.find_by(account_id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_account.nil?
  end

  # returns true if the current account has customer data
  def account_customer_info?
    !current_customer.nil?
  end
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency (order_item.price * order_item.quantity) %></span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", index_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>

  <div class="row">
    <div class="col-xs-12">
      <% if logged_in? %>
      <%= link_to 'Review Cart', process_cart_path, class: 'btn btn-success pull-right' %>
      <!-- <a href="#" class="btn btn-success pull-right"></a> -->
      <% else %>
        <%= link_to 'Login', login_path, class: 'btn btn-success pull-right' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/carts/checkout.html.erb
<div class="shopping-cart">
  <h1>Final Checkout</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Quantity</th>
        <th>Price Per Unit</th>
        <th>Subtotal</th>
      </tr>
    </thead>
    <tbody>
      <% @order_items.each do |item| %>
        <tr>
          <td><%= item.product.name %></td>
          <td><%= item.quantity %></td>
          <td><%= item.price %></td>
          <td><%= (item.price * item.quantity) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>

        <tr>
          <td>PST: </td>
          <td><%= @order.pst %></td>
        </tr>

      <% if @order.gst %>
        <tr>
          <td>GST: </td>
          <td><%= @order.gst %></td>
        </tr>
      <% end %>
      <% if @order.hst %>
        <tr>
          <td>HST: </td>
          <td><%= @order.pst %></td>
        </tr>
      <% end %>
      <tr>
        <td>
          Sutotal:
        </td>
        <td>
          <%= @order.subtotal %>
        </td>
      </tr>
      <tr>
        <td>
          Total Taxes:
        </td>
        <td>
          <%= @order.subtotal * (@order.pst + @order.gst + @order.hst) %>
        </td>
      </tr>
      <tr>
        <td>
          Total:
        </td>
        <td>
          <%= @order.subtotal + (@order.subtotal * (@order.pst + @order.gst + @order.hst) )%>
        </td>
      </tr>
    </tbody>
  </table>
    <%= form_tag charges_path do %>
      <article>
        <% if flash[:error].present? %>
          <div id="error_explanation">
            <p><%= flash[:error] %></p>
          </div>
        <% end %>
        <label class="amount">
          <span>Amount: <%= number_to_currency(@amount) %></span>
        </label>
      </article>

      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="<%= @description %>"
              data-amount="<%= (@amount*100).to_i %>"
              data-locale="auto"></script>
    <% end %>
</div>

app/views/carts/process_cart.html.erb
<div class="shopping-cart">
  <h1>Order Review</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Quantity</th>
        <th>Price Per Unit</th>
        <th>Subtotal</th>
      </tr>
    </thead>
    <tbody>
      <% @order_items.each do |item| %>
        <tr>
          <td><%= item.product.name %></td>
          <td><%= item.quantity %></td>
          <td><%= item.price %></td>
          <td><%= (item.price * item.quantity) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% if @order.pst %>
        <tr>
          <td>PST: </td>
          <td><% @order.pst %></td>
        </tr>
      <% end %>
      <% if @order.gst %>
        <tr>
          <td>GST: </td>
          <td><% @order.gst %></td>
        </tr>
      <% end %>
      <% if @order.hst %>
        <tr>
          <td>HST: </td>
          <td><% @order.pst %></td>
        </tr>
      <% end %>
      <tr>
        <td>
          Sutotal:
        </td>
        <td>
          <%= @order.subtotal %>
        </td>
      </tr>
    </tbody>
  </table>
  <%= link_to 'Checkout', checkout_path %>
  <!-- <% if account_customer_info? %>
    <%= link_to 'Checkout', checkout_path %>

  <% end %> -->
</div>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>