config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'carts#show', as: 'cart'
  resources :order_items, only: [:create, :update, :destroy]
  resources :customer, only: [:new, :create, :update, :destroy]
  resources :charges, only: [:new, :create]
  get 'login', to: 'session#new', as: 'login'
  post 'login', to: 'session#create', as: 'create_session'
  get 'logout', to: 'session#destroy', as: 'logout'
  get 'signup', to: 'accounts#new', as: 'signup'
  post 'signup', to: 'accounts#create', as: 'accounts'
  get 'process_cart', to: 'carts#process_cart', as: 'process_cart'
  get 'checkout', to: 'carts#checkout', as: 'checkout'
  post 'complete', to: 'carts#complete_order', as: 'complete_order'
  # resources :accounts, only: [:new, :create, :update, :destroy]

  get '/categories/:name/products', to: 'products#by_category', as: 'by_category'
  get '/', to: 'products#index', as: 'index'
  get '/products/:id', to: 'products#show', as: 'show'
  get '/about', to: 'pages#about', as: 'about'
  get '/contact_us', to: 'pages#contact_us', as: 'contact_us'
  # get '/:name', to: 'product#by_category', as: 'product_by_category'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
  belongs_to :province
end

app/models/order.rb
# order class
class Order < ApplicationRecord
  belongs_to :customer
  before_create :set_order_status
  belongs_to :order_status
  has_many :order_items
  before_save :update_subtotal

  def subtotal
    order_items
      .collect { |item| item.valid? ? (item.quantity.to_i * item.unit_price.to_f) : 0 }
      .sum
  end

  private

  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
# order_item class
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true,
                                                       greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def order_present
    errors.add(:order, 'is not a valid order.') if order.nil?
  end

  def product_present
    errors.add(:product, 'is not a valid product.') if product.nil?
  end

  def finalize
    self[:price] = unit_price
  end
end

app/models/order_status.rb
# order status class
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
# product class
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items

  default_scope { where(is_active: true) }

  def self.search(search)
    where('name LIKE ? or description LIKE ?', "%#{search}%", "%#{search}%")
  end

  def self.get_by_category_id(category_id)
    where('category_id = ?', category_id)
  end

  mount_uploader :image_url, ProductUploader
end

app/models/province.rb
# province class
class Province < ApplicationRecord
  has_many :customers
end

app/models/sale_item.rb
class SaleItem < ApplicationRecord
  belongs_to :product
end

app/controllers/products_controller.rb
# Product  class
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :retrieve_categories, only: [:index, :by_categroy]

  def index
    @products = Product.all.order('name').page(params[:page]).per(5)
    @order_item = current_order.order_items.new
    @products = retreive_products
  end

  def by_category
    @products = Category.where("name LIKE '#{params[:name]}'").first.products
                        .order('name')
                        .page(params[:page]).per(5)
    @order_item = current_order.order_items.new
    render 'index'
  end

  def show() end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  def retreive_products
    if !params[:category_id].to_i.zero? && params[:search]
      @produes = full_search
    elsif params[:search]
      @products = text_search
    elsif params[:category_id]
      @products = category_search
    else
      @products = all_products
    end
  end

  def product_params
    params.require(:product).permit(
      :name, :description, :category_id, :price, :quantity
    )
  end

  def retrieve_categories
    @categories = Category.all
  end

  def full_search
    @products = Product.get_by_category_id(params[:category_id])
                       .search(params[:search]).order('created_at DESC')
                       .page(params[:page]).per(5)
  end

  def text_search
    @products = Product.search(params[:search]).order('created_at DESC')
                       .page(params[:page]).per(5)
  end

  def category_search
    @products = Product.get_by_category_id(params[:category_id])
                       .order('created_at DESC')
                       .page(params[:page]).per(5)
  end

  def all_products
    @products = Product.all.order('created_at DESC').page(params[:page])
                       .per(5)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in(account)
    session[:user_id] = account.id
  end

  # Returns the current logged-in user (if any).
  def current_account
    @current_account ||= Account.find_by(id: session[:user_id])
  end

  def current_customer
    @current_customer = Customer.find_by(account_id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_account.nil?
  end

  # returns true if the current account has customer data
  def account_customer_info?
    !current_customer.nil?
  end
end

app/views/products/_product.html.erb
    <div class="col-xs-3">
        <div class="panel panel-default">
          <%= image_tag product.image_url, :class => "img-responsive"%>
          <div>
            <%= link_to product.name, show_path(product) %>
          </div>
          <div>
            <%= product.description %>
          </div>
          <%= form_for order_item, remote: true do |f| %>
            <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
              <div class="input-group">
                <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
                <div class="input-group-btn">
                  <%= f.hidden_field :product_id, value: product.id %>
                  <%= f.submit "Add to Cart", class: "btn btn-primary" %>
                </div>
              </div>
          <% end %>
        </div>
    </div>

app/views/products/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Daevok's Supplies</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class=""><%= link_to 'Contact Us', contact_us_path %></li>
            <li class=""><%= link_to 'About Us', about_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% @categories.each do |c| %>
                  <li><%= link_to c.name, by_category_path(:name => c.name) %></li>
                <% end %>
              </ul>
            </li>
          </ul>
          <%= form_tag(index_path, :method => "get", id: "search-form", :class => "navbar-form navbar-right") do %>
            <!-- <div class="form-group"> -->
              <div class="input-group">
                <div class="input-group-btn">
                  <!-- <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">All <span class="caret"></span></button> -->
                  <!-- <select class="form-control">
                    <option value=0>All</option>
                      <%= options_from_collection_for_select(@categories, :id, :name) %>
                  </select> -->
                  <%= select_tag(:category_id, content_tag(:option,'All',:value=>"0") + options_from_collection_for_select(@categories, :id, :name), options = {:class => "form-control"}) %>
                </div><!-- button group -->
                <%= text_field_tag :search, params[:search], placeholder: "Search Products", :class => "form-control" %>
                <span class="input-group-btn">
                  <input type="submit" class="btn btn-default" value="Search" />
                  <!-- <%= submit_tag "Search", :class => "btn btn-default" %> -->
                </span>
              </div>
          <% end %>

        </div>

          <!-- <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form> -->
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
</div>





<% if @products.present? %>
  <% @products.each_slice(4) do |products| %>
    <div class="row">
      <% products.each do |product|%>
        <%= render 'product', product: product, order_item: @order_item %>
      <% end %>
    </div>
  <% end %>
<% else %>
  <p>There are no products containing the term(s) <%= params[:search] %>.</p>
<% end %>
<%= paginate @products %>
<script type="text/javascript">
  $(".dropdown-menu li").click(function(){
    var selText = $(this).text();
    $(this).parents('.input-group-btn').find('.dropdown-toggle').html(selText+'<span class="caret"></span>');
  });
</script>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag @product.image_url %>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Quantity in stock:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Price per Unit</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Category</strong>
  <%= @product.category.name %>
</p>

<%= link_to 'Home', index_path(@customer) %>