config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'carts#show', as: 'cart'
  resources :order_items, only: [:create, :update, :destroy]
  resources :customer, only: [:new, :create, :update, :destroy]
  resources :charges, only: [:new, :create]
  get 'login', to: 'session#new', as: 'login'
  post 'login', to: 'session#create', as: 'create_session'
  get 'logout', to: 'session#destroy', as: 'logout'
  get 'signup', to: 'accounts#new', as: 'signup'
  post 'signup', to: 'accounts#create', as: 'accounts'
  get 'process_cart', to: 'carts#process_cart', as: 'process_cart'
  get 'checkout', to: 'carts#checkout', as: 'checkout'
  post 'complete', to: 'carts#complete_order', as: 'complete_order'
  # resources :accounts, only: [:new, :create, :update, :destroy]

  get '/categories/:name/products', to: 'products#by_category', as: 'by_category'
  get '/', to: 'products#index', as: 'index'
  get '/products/:id', to: 'products#show', as: 'show'
  get '/about', to: 'pages#about', as: 'about'
  get '/contact_us', to: 'pages#contact_us', as: 'contact_us'
  # get '/:name', to: 'product#by_category', as: 'product_by_category'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
  belongs_to :province
end

app/models/order.rb
# order class
class Order < ApplicationRecord
  belongs_to :customer
  before_create :set_order_status
  belongs_to :order_status
  has_many :order_items
  before_save :update_subtotal

  def subtotal
    order_items
      .collect { |item| item.valid? ? (item.quantity.to_i * item.unit_price.to_f) : 0 }
      .sum
  end

  private

  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
# order_item class
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true,
                                                       greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def order_present
    errors.add(:order, 'is not a valid order.') if order.nil?
  end

  def product_present
    errors.add(:product, 'is not a valid product.') if product.nil?
  end

  def finalize
    self[:price] = unit_price
  end
end

app/models/order_status.rb
# order status class
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
# product class
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items

  default_scope { where(is_active: true) }

  def self.search(search)
    where('name LIKE ? or description LIKE ?', "%#{search}%", "%#{search}%")
  end

  def self.get_by_category_id(category_id)
    where('category_id = ?', category_id)
  end

  mount_uploader :image_url, ProductUploader
end

app/models/province.rb
# province class
class Province < ApplicationRecord
  has_many :customers
end

app/models/sale_item.rb
class SaleItem < ApplicationRecord
  belongs_to :product
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in(account)
    session[:user_id] = account.id
  end

  # Returns the current logged-in user (if any).
  def current_account
    @current_account ||= Account.find_by(id: session[:user_id])
  end

  def current_customer
    @current_customer = Customer.find_by(account_id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_account.nil?
  end

  # returns true if the current account has customer data
  def account_customer_info?
    !current_customer.nil?
  end
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path(), class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="row">
        <div class="col-xs-6">

        </div>
        <div class="col-xs-6 text-right">
          <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
          <% if logged_in? %>
            <%= link_to 'Logout', logout_path %>
          <% end %>
        </div>
      </div>
    </div>
    <hr />
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @page.title %></h1>
<p><%= @page.content %></p>

app/views/pages/contact_us.html.erb
<h1><%= @page.title %></h1>
<p><%= @page.content %></p>

app/views/pages/login.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Log in</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(:session, url: login_path) do |f| %>

          <%= f.label :username %>
          <%= f.email_field :username, class: 'form-control' %>

          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>

          <%= f.submit "Log in", class: "btn btn-primary" %>
        <% end %>

        <p>New user? <%= link_to "Sign up now!", signup_path %></p>
      </div>
    </div>
  </div>
</div>